app.py, conf/jwt.py, conf/mongo.py, presets/status.py, routes/post.py, utils/token.py
- 글 작성 API
- 글 내용 획득 API
- 글 수정 API
- 글 삭제 API
- 글 목록 획득 API
=> Post API 구현

app.py, routes/message.py
- 쪽지 보내기 API
- 쪽지 내용 획득 API
- 쪽지 삭제 API
- 쪽지 목록 획득 API
=> Message API 구현

app.py, presets/status.py, routes/comment.py, routes/user.py
- 댓글 작성 API
- 댓글 획득 API
- 댓글 삭제 API
=> Comment API 구현

app.py, routes/post_close.py
=> 모집 마감 기능 구현

app.py, routes/like.py
=> 좋아요 API 구현

app.py, routes/login.py
=> 로그인 API 구현

app.py, routes/bookmark.py
=> Bookmark API 구현

routes/post.py
- 글 내용 획득 API 닉네임 반환
- 글 내용 획득 API 좋아요 수 반환
- 글 내용 획득 API 좋아요 여부 반환
- 글 내용 획득 API 북마크 여부 반환
- 글 목록 획득 API 좋아요 수 반환
- 글 목록 획득 API 좋아요 여부 반환
- 글 목록 획득 API 북마크 여부 반환
=> 게시글 API 수정

routes/user.py
=> 현재 사용자 ID 획득 API 구현

src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/controller/PostController.java, src/main/java/com/igocst/coco/domain/Member.java, src/main/java/com/igocst/coco/domain/Post.java, src/main/java/com/igocst/coco/repository/PostRepository.java, src/main/java/com/igocst/coco/security/MemberDetailsService.java, src/main/java/com/igocst/coco/security/SecurityConfiguration.java, src/main/java/com/igocst/coco/security/filter/JwtAuthenticationFilter.java, src/main/java/com/igocst/coco/security/jwt/JwtTokenProvider.java, src/main/java/com/igocst/coco/service/PostService.java, src/main/resources/application.properties
=> 게시글 API 구현

src/main/java/com/igocst/coco/controller/CommentController.java, src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/controller/PostController.java, src/main/java/com/igocst/coco/domain/Member.java, src/main/java/com/igocst/coco/domain/Post.java, src/main/java/com/igocst/coco/dto/member/MemberDeleteResponseDto.java, src/main/java/com/igocst/coco/dto/message/MessageListReadResponseDto.java, src/main/java/com/igocst/coco/service/CommentService.java, src/main/java/com/igocst/coco/service/MemberService.java, src/main/java/com/igocst/coco/service/MessageService.java, src/main/java/com/igocst/coco/service/PostService.java
관리자만 수행 가능한 기능
- 모든 게시글 삭제 가능
- 모든 댓글 삭제 가능
- 회원 강제 탈퇴 가능
=> 관리자 API 구현

src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/domain/Member.java, src/main/java/com/igocst/coco/dto/member/MemberReadResponseDto.java, src/main/java/com/igocst/coco/dto/member/MemberUpdateRequestDto.java, src/main/java/com/igocst/coco/dto/member/MemberUpdateResponseDto.java, src/main/java/com/igocst/coco/security/MemberDetailsService.java, src/main/java/com/igocst/coco/security/SecurityConfiguration.java, src/main/java/com/igocst/coco/service/MemberService.java
**보완할 점**
- 정보 수정 기능에 Password, ImageUrl 도 넣어줘야하는데 현재 능력부족으로 보류 상태로 빼놓음.
=> 회원 정보 획득 / 수정 API 구현

src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/domain/Member.java, src/main/java/com/igocst/coco/dto/member/MemberDeleteResponseDto.java, src/main/java/com/igocst/coco/service/MemberService.java
=> 회원 탈퇴 API 구현

src/main/java/com/igocst/coco/domain/Post.java, src/main/java/com/igocst/coco/dto/post/PostUpdateRequestDto.java, src/main/java/com/igocst/coco/repository/PostRepository.java, src/main/java/com/igocst/coco/security/SecurityConfiguration.java, src/main/java/com/igocst/coco/service/PostService.java
=> 게시글 조회수 기능 구현

src/main/java/com/igocst/coco/repository/PostRepository.java, src/main/java/com/igocst/coco/service/PostService.java
=> 게시글 목록 조회 수정

src/main/java/com/igocst/coco/dto/comment/CommentReadResponseDto.java, src/main/java/com/igocst/coco/service/CommentService.java
프론트엔드랑 연결시 comment id 서버에서 프론트로 못 보내줘서 CommentService / CommentReadResponseDto 수정했습니다.
=> 댓글 API 업데이트

src/main/java/com/igocst/coco/dto/comment/CommentCreateRequestDto.java, src/main/java/com/igocst/coco/dto/comment/CommentReadResponseDto.java, src/main/java/com/igocst/coco/service/CommentService.java
** 기능 **
댓글 작성하면 다시 불러올 때 @닉네임 옆에 Time ago 생성
-  1분 미만은 `방금전` 으로 표시되고 그 이후엔 `~분/시간/일/년 전`...으로 표시됨
** 변경된 점**
서버 Comment.java에서 Timestamped 상속 받지 않고, Comment entity에서 createDate 필드를 만들어 사용함
- modifiedDate 필드 사라짐 추후 수정기능 구현시 다시 생성 가능!
=> 댓글 Time ago 기능 구현

src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/dto/member/CheckDupResponseDto.java, src/main/java/com/igocst/coco/dto/member/CheckEmailDupRequestDto.java, src/main/java/com/igocst/coco/dto/member/CheckNicknameDupRequestDto.java, src/main/java/com/igocst/coco/repository/MemberRepository.java, src/main/java/com/igocst/coco/security/SecurityConfiguration.java, src/main/java/com/igocst/coco/service/MemberService.java
- 회원가입 URL 변경
- 회원가입 시 이메일, 닉네임 중복 체크 API 기능 구현
=> 회원가입 URL 변경, 회원가입 시 이메일, 닉네임 중복 체크 기능 구현

src/main/java/com/igocst/coco/service/MemberService.java
로그인시, 아무 패스워드를 입력해도 로그인 되던 오류를 수정
=> 로그인 API 수정

src/main/java/com/igocst/coco/service/MessageService.java
- 기존 발신 & 수신자 타입 Email -> Nickname 으로 보이도록 변경
=> 쪽지 발신 & 수신자 타입 변경

src/main/java/com/igocst/coco/controller/CommentController.java, src/main/java/com/igocst/coco/dto/comment/CommentReadResponseDto.java, src/main/java/com/igocst/coco/service/CommentService.java
사용자를 검사해 댓글을 작성한 사용자면, 댓글을 삭제할 수 있도록 하고, 댓글을 작성한 사용자가 아니면 삭제가 안되도록 클라이언트에 데이터 전달
=> 댓글 삭제 기능 추가

src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/service/MemberService.java
=> 회원 탈퇴기능 변경

src/main/java/com/igocst/coco/security/SecurityConfiguration.java, src/main/java/com/igocst/coco/security/filter/JwtAuthenticationFilter.java, src/main/java/com/igocst/coco/security/jwt/JwtTokenProvider.java, src/main/java/com/igocst/coco/service/MemberService.java, src/main/java/com/igocst/coco/service/PostService.java
- 쿠키를 사용하는 방식은 AWS 배포 시 문제가 생겼음
- Cookie를 사용하던 방식에서 Header Authorization 사용으로 변경
=> Cookie -> Header Authorization 변경

src/main/java/com/igocst/coco/dto/post/PostReadResponseDto.java, src/main/java/com/igocst/coco/service/PostService.java
#87 
- 글 상세페이지에서 글 작성자의 프로필을 모달을 통해 확인할 수 있도록 하기위해서 Dto 멤버변수 추가
=> 게시글 API 추가기능 구현

src/main/java/com/igocst/coco/controller/BookmarkController.java, src/main/java/com/igocst/coco/domain/Bookmark.java, src/main/java/com/igocst/coco/domain/Member.java, src/main/java/com/igocst/coco/domain/Post.java, src/main/java/com/igocst/coco/dto/bookmark/BookmarkDeleteResponseDto.java, src/main/java/com/igocst/coco/dto/bookmark/BookmarkListReadResponseDto.java, src/main/java/com/igocst/coco/dto/bookmark/BookmarkSaveRequestDto.java, src/main/java/com/igocst/coco/dto/bookmark/BookmarkSaveResponseDto.java, src/main/java/com/igocst/coco/repository/BookmarkRepository.java, src/main/java/com/igocst/coco/service/BookmarkService.java
#120 
- 북마크 저장, 삭제, 리스트 불러오기 기능 구현
- 북마크에 동일한 게시물을 저장할 시 예외발생
=> 북마크 API 구현

src/main/java/com/igocst/coco/security/jwt/JwtTokenProvider.java
#131 
서비스 이용 중 로그아웃 방지 위해 토큰 만료시간 변경
* 추후에 리프레쉬 토큰 구현 예정!
=> jwt 토큰 만료시간 변경

src/main/java/com/igocst/coco/service/BookmarkService.java
#134
- Entity에 북마크가 추가되지않고,
한 포스트당 한 멤버만 저장되는 현상 수정
=> 북마크 API 수정

.gitignore, src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/domain/Post.java, src/main/java/com/igocst/coco/service/MemberService.java, src/main/resources/application.properties, src/main/resources/aws.yml
- 현재 사용중인 닉네임에서 중복체크 했을 때 `사용할 수 있음`으로 뜨게 함
=> 프로필 닉네임 수정 오류 수정

src/main/java/com/igocst/coco/domain/Post.java
=> 게시글 엔티티 content 필드 길이 변경

src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/repository/PostRepository.java, src/main/java/com/igocst/coco/service/MemberService.java
#141 
- 프로필 페이지에서 본인이 작성한 게시글 내려주도록 기능 추가
=> 게시글 목록 조회 API 추가

src/main/java/com/igocst/coco/dto/comment/CommentReadResponseDto.java, src/main/java/com/igocst/coco/dto/post/PostReadResponseDto.java, src/main/java/com/igocst/coco/service/CommentService.java, src/main/java/com/igocst/coco/service/PostService.java
#144 댓글에 유저 프로필 보여주기
#145 게시글 유저 프로필 조회시 프로필 이미지 보여주기
=> 댓글 & 프로필 모달 User 프로필 이미지 보기

src/main/java/com/igocst/coco/controller/MemberController.java, src/main/java/com/igocst/coco/dto/post/PostSaveRequestDto.java, src/main/java/com/igocst/coco/service/BookmarkService.java, src/main/java/com/igocst/coco/service/CommentService.java, src/main/java/com/igocst/coco/service/MemberService.java, src/main/java/com/igocst/coco/service/MessageService.java, src/main/java/com/igocst/coco/service/PostService.java, src/main/resources/application.properties, src/main/resources/aws.yml, src/main/resources/logback-spring.xml
=> Logging 구현

README.md
=> READ ME 작성

build.gradle, src/main/java/com/igocst/coco/WebConfig.java, src/main/java/com/igocst/coco/domain/Post.java, src/main/java/com/igocst/coco/s3/S3Service.java, src/main/java/com/igocst/coco/security/SecurityConfiguration.java, src/main/java/com/igocst/coco/service/CommentService.java, src/main/java/com/igocst/coco/service/MemberService.java, src/main/java/com/igocst/coco/service/MessageService.java, src/main/java/com/igocst/coco/service/PostService.java, src/main/java/com/igocst/coco/util/FileUtils.java, src/main/resources/application.properties
#158 XSS 문제
#159 이미지 확장자 체크 필터
- XSS 방어 필터 적용
- 파일 첨부 시, 이미지 확장자 체크 (이미지 파일만 첨부 가능)
=> XSS 방어 필터 적용 / 프로필 수정 시, 파일 첨부 기능 수정

src/main/java/com/igocst/coco/common/status/StatusMessage.java, src/main/java/com/igocst/coco/controller/MessageController.java, src/main/java/com/igocst/coco/dto/message/MessageListReadResponseDto.java, src/main/java/com/igocst/coco/service/MessageService.java
#161 #162 
- 기존 받은 쪽지 리스트만 구현했던 것에 추가적으로 보낸 쪽지 리스트를 불러오도록 구현
- Status Message 'UNKNOWN_RECEIVER' 추가
↳ 쪽지 보낼 때, DB에 존재하지 않는 사용자일 경우 전송되는 메시지
↳ MessageService에서 보내줌
=> 보낸 쪽지 리스트 구현

src/main/java/com/igocst/coco/controller/PostController.java, src/main/java/com/igocst/coco/repository/PostRepository.java, src/main/java/com/igocst/coco/security/SecurityConfiguration.java, src/main/java/com/igocst/coco/service/PostService.java
#164 
- 시큐리티에서 게시글 검색 URL 허용
- 검색 API 구현
=> 게시글 검색 기능 구현

src/main/java/com/igocst/coco/dto/comment/CommentReadResponseDto.java, src/main/java/com/igocst/coco/service/CommentService.java
#169 댓글 수정 기능
수정된걸 알려주기 위해 ModifyDate 추가했습니다.
=> 댓글 수정 기능 업그레이드 버전

src/main/java/com/igocst/coco/repository/PostRepository.java, src/main/java/com/igocst/coco/service/MemberService.java, src/main/java/com/igocst/coco/service/PostService.java
#167 
- 작성시간을 기준으로 게시글 목록 조회
- 게시글을 수정하면 목록 최상단으로 이동되던 부분 수정
=> 게시글 목록 조회 API 변경

src/main/java/com/igocst/coco/controller/PostController.java, src/main/java/com/igocst/coco/service/PostService.java
#175 
- 조회 수 중복 증가를 방지하기 위해 쿠키 사용 (Cookie, HttpServletRequest, HttpServletResponse)
- 한 번 게시글을 조회했으면 재접근했을 때 조회 수가 증가되지 않도록 함
=> 게시글 조회 수 중복 방지

src/main/java/com/igocst/coco/controller/CommentController.java, src/main/java/com/igocst/coco/service/CommentService.java
Front 불필요한 ajax 코드 삭제하면서 삭제된 코드들입니다.
=> 불필요한 코드 제거

src/main/java/com/igocst/coco/WebConfig.java, src/main/java/com/igocst/coco/security/SecurityConfiguration.java, src/main/java/com/igocst/coco/service/PostService.java, src/main/resources/application.properties
- 배포 환경에서 쿠키가 동작하지 않는 문제 확인 -> 쿠키 도메인 추가로 해결
- CORS 설정 변경
-  '*'  ->  'www.cocoding.xyz'
=> 쿠키 도메인 추가 & CORS 설정 수정
